apiVersion: v1
kind: Secret
metadata:
  name: chatbot-secrets
  namespace: chatbot-staging
type: Opaque
data:
  jwt-secret: bXlTZWNyZXRLZXk=  # base64 encoded "mySecretKey"
  mongodb-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGI6MjcwMTcvY2hhdGJvdF9kYg==  # base64 encoded MongoDB URI
---
apiVersion: v1
kind: Secret
metadata:
  name: chatbot-secrets
  namespace: chatbot-production
type: Opaque
data:
  jwt-secret: eW91clByb2R1Y3Rpb25TZWNyZXRLZXk=  # base64 encoded production secret
  mongodb-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGI6MjcwMTcvY2hhdGJvdF9wcm9k  # base64 encoded production MongoDB URI
